modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="doughs"
version="${file.jarVersion}"
displayName="Doughs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/doughs"
authors="IchHabeHunger54"
description='''
Requires you to bake bread, cake, cookies and pumpkin pies before you can actually eat them.
'''
[[dependencies.doughs]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.doughs]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
